services:
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - yolo-network

  backend:
    image: rmwangi3/yolo-backend:1.0.0
    build:
      context: ./backend
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT:-5000}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/public/images:/usr/src/app/public/images
    networks:
      - yolo-network

  client:
    image: rmwangi3/yolo-client:1.0.0
    build:
      context: ./client
    ports:
      - "3000:80"
    networks:
      - yolo-network

volumes:
  mongo-data:

networks:
  yolo-network:
    driver: bridge
